# Generated by Django 5.1.2 on 2024-11-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movies",
            name="value6",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
